---
- name: Install VNC
  import_playbook: ./plays/install_vnc.yaml
- name: Install OCP Tools
  import_playbook: ./plays/install_ocptools.yaml
- name: Install Virtualization
  import_playbook: ./plays/install_virt.yaml
- name: Install DNS
  import_playbook: ./plays/install_dns.yaml
- name: Create VMs for cluster
  import_playbook: ./plays/create_vms.yaml
- name: Setup lab environment
  import_playbook: ./plays/setup_lab.yaml
