---
- name: setup lab environment
  hosts: aws_ec2
  tasks:
    - name: Create my-cluster directory
      ansible.builtin.file:
        path: /home/ec2-user/my-cluster
        state: directory
        mode: 0755
        owner: "ec2-user"
        group: "ec2-user"
    - name: Generate an OpenSSH keypair with the default values (4096 bits, rsa)
      community.crypto.openssh_keypair:
        path: /home/ec2-user/.ssh/id_rsa
      register: sshkey
    - name: Copy install-config
      become: true
      ansible.builtin.template:
        src: files/install-config.yaml
        dest: /home/ec2-user/my-cluster/install-config.yaml
    - name: Copy agent-config
      become: true
      ansible.builtin.copy:
        src: files/agent-config.yaml
        dest: /home/ec2-user/my-cluster/agent-config.yaml