apiVersion: v1
baseDomain: ocpbaremetal.com
compute:
- architecture: amd64 
  hyperthreading: Enabled
  name: worker
  replicas: 2
  platform:
    baremetal: {}
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  replicas: 3
  platform:
    baremetal: {}
metadata:
  name: ocp
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 192.168.122.0/24
  networkType: OVNKubernetes 
  serviceNetwork:
  - 172.30.0.0/16
platform: 
  baremetal:
    apiVIPs:
      - 192.168.122.250
    ingressVIPs:
      - 192.168.122.251
pullSecret: '{{ ocp_pull_secret }}' 
sshKey: '{{ sshkey.public_key }}'